<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRG7vc54\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRG7vc54/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRG7vc54.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRG7vc54\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRG7vc54\App_KernelDevDebugContainer([
    'container.build_hash' => 'RG7vc54',
    'container.build_id' => '053dcb02',
    'container.build_time' => 1591612348,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRG7vc54');
