<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin_dashboard' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/dashboard']], [], []],
    'carModels' => [['id'], ['_controller' => 'App\\Controller\\AdminController::getModels'], [], [['text', '/models'], ['variable', '/', '[^/]++', 'id', true]], [], []],
    'addCar' => [[], ['_controller' => 'App\\Controller\\AdminController::addCars'], [], [['text', '/cars/add']], [], []],
    'updateCar' => [['id'], ['_controller' => 'App\\Controller\\AdminController::updateCar'], [], [['text', '/car/update'], ['variable', '/', '[^/]++', 'id', true]], [], []],
    'carInfo' => [['id'], ['_controller' => 'App\\Controller\\AdminController::getCarByID'], [], [['text', '/carInfo'], ['variable', '/', '[^/]++', 'id', true]], [], []],
    'uCarInfo' => [['id'], ['_controller' => 'App\\Controller\\AdminController::getCarByIDToUpdate'], [], [['text', '/car/info'], ['variable', '/', '[^/]++', 'id', true]], [], []],
    'deletCar' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteCarById'], [], [['text', '/car/delete'], ['variable', '/', '[^/]++', 'id', true]], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\AuthenticationController::registration'], [], [['text', '/register']], [], []],
    'loginPath' => [[], ['_controller' => 'App\\Controller\\AuthenticationController::loginCheck'], [], [['text', '/login']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\AuthenticationController::logout'], [], [['text', '/logout']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], []],
    'login_redirect' => [[], ['_controller' => 'App\\Controller\\LoginController::loginRedirectAction'], [], [['text', '/login/redirect']], [], []],
    'profile' => [[], ['_controller' => 'App\\Controller\\ProfileController::index'], [], [['text', '/profile']], [], []],
    'cancelReservation' => [['id'], ['_controller' => 'App\\Controller\\ProfileController::cancelReservation'], [], [['text', '/reservation/cancel'], ['variable', '/', '[^/]++', 'id', true]], [], []],
    'profile_contact_form' => [[], ['_controller' => 'App\\Controller\\ProfileController::contactMail'], [], [['text', '/profile/contact']], [], []],
];
